spring.application.name: lolibox
server.port: 8888
server.address: 127.0.0.1
spring.http.multipart.max-file-size: 20MB
management.context-path: /admin/

# 在 linux 系统中，spring boot 应用在启动的时候，会在系统的 /tmp 目录下生成一个 tomcat.* 的文件目录，
# 上传的文件会在这个临时文件夹中保存一份，临时目录下的文件在长时间没有使用时就会被系统自动删除掉，这时候再上传文件就可能会报错，
# 报错信息一般类似这样：The temporary upload location [/tmp/tomcat.5425935716444258807.8888/work/Tomcat/localhost/ROOT] is not
server:
  tomcat:
    basedir: ${user.home}/lolibox/tmp

security:
  headers:
    cache: true
  ignored: /webjars/**,/css/**,/js/**,/img/**

#oauth2:
#  clients:
#    -
#      name: test-client
#      secret: test-password


spring.resources.chain.strategy.content.enabled: true
spring.resources.chain.strategy.content.paths: /**

logging:
  file: ${user.home}/lolibox/lolibox.log
  level.io.loli: debug
  pattern:
    level:
admin:
  email: excalibll@163.com
  anonymous: false
  signup-invitation: false
  invitation-seed: lolibox
  cdnHost:
  imgHost:
  green:
    enabled: none

storage:
  type: filesystem
  filesystem.imgFolder: ${user.home}/lolibox/
  aliyun:
    url:
    key:
    secret:
    name:
  qiniu:
    key:
    secret:
    name:
  baidu:
    key:
    secret:
    url:
    name:

spring:
  h2:
    console:
      enabled: true
      path: /admin/h2-console
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: io.loli.box.CustomNamingStrategy
  datasource:
    url: jdbc:h2:file:~/lolibox/db;FILE_LOCK=FS
    username: sa
    password: sa
  messages:
    basename: i18n/message

  thymeleaf:
    cache: false

spring.social.weibo:
  app-id:
  app-secret:

# 取消添加 x-application-context 头信息
management:
  add-application-context-header: false




#login.social.enabled: weibo
---
spring.profiles: zuul
zuul:
  routes:
    images:
      path: /images/**
      url:

